volumes:
  redis_data:
  logs:

services:
  db:
    image: redis:7.4.7-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - --appendonly
      - yes
      - --requirepass
      - ${DB_PASSWORD}
  bot:
    image: sitkliph/tickets_collector_tbot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./service_account.json:/run/secrets/sa_key.json:ro
      - logs:/app/logs
    command:
      - uvicorn
      - telegram_bot.webhook:api
      - --host
      - 0.0.0.0
      - --port
      - 8000 
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/sa_key.json
      WEBHOOK_MODE: true
      IS_PROD_STORAGE: true
